### ISSUE TITLE
suggested changes prior to publishing to Steampipe Registry

### ISSUE THREAD

**Issue by johnsmyth** [theapsgroup/steampipe-plugin-vault#4]
This is John from the Steampipe team -- We're excited to have you contributing to the Steampipe plugin community!  We will need to work through the mechanics of how exactly the registry publishing process works, as you are the first external contributor -- We will contact you with more details in this regard.

I took a quick look at your plugin today and had a few items that should be addressed:

- Tables names should be singular, not plural

- Generally, date/time fields should use ColumnType_TIMESTAMP.  
  - `server_time_utc` uses ColumnType_INT should probably be converted, and use a ColumnType_TIMESTAMP ( https://github.com/theapsgroup/steampipe-plugin-vault/blob/main/vault/table_health.go#L41 )

- Im not sure why the `noop`  - I don't think you really need the `Get` at all here? -  https://github.com/theapsgroup/steampipe-plugin-vault/blob/main/vault/table_health.go#L29 
 
- The tables don't seem to have many columns.  For example, I would minimally expect to see the same data in the `vault_kv_secrets` as the `vault kv get` command would return (including the secret data values):
as
```bash
$ vault kv get secret/hello
====== Metadata ======
Key              Value
---              -----
created_time     2021-05-10T20:10:28.307902Z
deletion_time    n/a
destroyed        false
version          2

===== Data =====
Key        Value
---        -----
excited    yes
foo        world
```

- My knowledge of vault is limited, but I notice that the column names don't always conform to the language used in the CLI.  Im not sure what is correct in this case, but it is definitely worth paying attention to, as renaming columns after the plugin is released is a hassle for users. For example, the `mountpoint` in `vault_engines` seems to be referred to as  `path` in the CLI output:

```
$ steampipe query "select * from vault_engines"
+------------+-----------+
| mountpoint | type      |
+------------+-----------+
| sys/       | system    |
| secret/    | kv        |
| identity/  | identity  |
| cubbyhole/ | cubbyhole |
+------------+-----------+

Time: 483.783688ms

Johns-MBP-2:steampipe-plugin-vault jsmyth$ vault secrets list
Path          Type         Accessor              Description
----          ----         --------              -----------
cubbyhole/    cubbyhole    cubbyhole_03ad4f03    per-token private secret storage
identity/     identity     identity_37451878     identity store
secret/       kv           kv_63726df9           key/value secret storage
sys/          system       system_ac4bc3bf       system endpoints used for control, policy and debugging
```

Likewise, `vault_kv_secrets` uses the name `path` where the CLI refers to `key`:

```
$ steampipe query "select * from vault_kv_secrets"
+--------+------------+
| path   | mountpoint |
+--------+------------+
| /hello | secret/    |
+--------+------------+


$ vault kv list secret
Keys
----
hello
```

I look forward to continued collaboration, and feel free to reach out in the Slack or Github!

**Comment by Bonemind** [comment]
Hi, thanks for the feedback!

The noop in there was because of the following line in the docs:

```
Every table must define a Get function. The List function is not required, but is quite common.
```

We blindly assumed it was required, turns out it isn't. The rest of your feedback seems quite valid ;)

We do intentionally not expose the secrets themselves, we intend to provide steampipe as part of our platform, but don't intend it to be a way to fetch the secrets, that should happen via vault's mechanisms directly imho, so that explains some of the fewer columns.

The metadata would be useful to expose though.

**Comment by graza-io** [comment]
@johnsmyth - would it be possible for you to take a look again now we've had the chance to address your concerns and also implement the tables we require fully.

**Comment by johnsmyth** [comment]
sure @graza-io - I'll try to take a look at this today.

**Comment by johnsmyth** [comment]
Looks good @graza-io.  Some minor points:
- You should remove the `Columns` section in the table docs - we will generate this from the column descriptions (same text as `.inspect'`), so if you leave it in the markdown, it will appear twice.
- The `Build & Installation` in the `index.md` should probably just have 'plugin install' instructions.  Instructions for building from source are useful in the README, but we dont usually include them in the index page.
- You can leave the `Tables` section in the `index.md` if you want, but the hub site will show all the tables in the nav anyway - less maintenance to remove it but totally up to you.
- I didn't do a thorough grammar review but I did spot a couple typos:
    - `index.md` - typo in description: 'availabe'
    - `docs/tables/vault_auth.md`: `specifc` 
    
When you guys are ready to release, please tag the commit that you want released as `v0.0.1` and then give me a heads up and I'll publish it.  I need to get the publish job set up but that shouldn't take too long.

Thanks for your contribution!  Let me know if you need anything else.

**Comment by graza-io** [comment]
Hi @johnsmyth - Thanks, that's excellent news (stripping the column definitions out of the docs would be amazing, since it takes a while to add them 😄)

I'll make the changes once I get a chance and then we'll ping for release!

**Comment by graza-io** [comment]
Closing this as we've successfully got this in the hub 😃
